irentex/config/routes.rb
Rails.application.routes.draw do
  resources :renters
  resources :item_attachments
  get 'sessions/new'

  resources :categorys do
  resources :category_filters
  end
  
  get 'home/index'
  root 'home#index'
  resources :users do
      resources :items 
  end
  
resources :reservations

  patch   '/uploadlogo',      to: 'users#uploadlogo'

  get     '/markavailable',   to: 'items#markavailable'
  get	    '/showcat',         to: 'category_items#show'
  get     '/viewitem',        to: 'items#index'
  get     '/changeStatus',    to: 'reservations#changeStatus'

  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  get     '/loginrenter',     to: 'sessions#loginrenter'
  post    '/loginrenter',     to: 'sessions#createrenter'
  post    '/searchItems',     to: 'category_items#searchCat'
  delete  '/logout',          to: 'sessions#destroy'

end

irentex/app/models/renter.rb
class Renter < ActiveRecord::Base
	has_secure_password
end

irentex/app/controllers/renters_controller.rb
class RentersController < ApplicationController
  before_action :set_renter, only: [:show, :edit, :update, :destroy]

  # GET /renters
  # GET /renters.json
  def index
    @renters = Renter.all
  end

  # GET /renters/1
  # GET /renters/1.json
  def show
  end

  # GET /renters/new
  def new
    @renter = Renter.new
  end

  # GET /renters/1/edit
  def edit
  end

  # POST /renters
  # POST /renters.json
  def create
    @renter = Renter.new(renter_params)

    respond_to do |format|
      if @renter.save
        format.html { redirect_to @renter, notice: 'Renter was successfully created.' }
        format.json { render :show, status: :created, location: @renter }
      else
        format.html { render :new }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /renters/1
  # PATCH/PUT /renters/1.json
  def update
    respond_to do |format|
      if @renter.update(renter_params)
        format.html { redirect_to @renter, notice: 'Renter was successfully updated.' }
        format.json { render :show, status: :ok, location: @renter }
      else
        format.html { render :edit }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renters/1
  # DELETE /renters/1.json
  def destroy
    @renter.destroy
    respond_to do |format|
      format.html { redirect_to renters_url, notice: 'Renter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_renter
      @renter = Renter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def renter_params
      params.require(:renter).permit(:renter_name, :renter_email, :password)
    end
end

irentex/app/helpers/renters_helper.rb
module RentersHelper
end

irentex/app/views/renters/_form.html.erb
<%= form_for(@renter) do |f| %>
  <% if @renter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@renter.errors.count, "error") %> prohibited this renter from being saved:</h2>

      <ul>
      <% @renter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :renter_name %><br>
    <%= f.text_field :renter_name %>
  </div>
  <div class="field">
    <%= f.label :renter_email %><br>
    <%= f.text_field :renter_email %>
  </div>
  
  <div class="field">
  <%= f.label :"Password"  %>
  <%= f.password_field :password, class: 'form-control' %><br> 
  </div>
  
  <div class="field">
  <%= f.label :"Password confirmation"  %> <br> 
  <%= f.password_field :password_confirmation , class: 'form-control' %> <br> 

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

irentex/app/views/renters/edit.html.erb
<h1>Editing Renter</h1>

<%= render 'form' %>

<%= link_to 'Show', @renter %> |
<%= link_to 'Back', renters_path %>

irentex/app/views/renters/new.html.erb
<h1>New Renter</h1>

<%= render 'form' %>

<%= link_to 'Back', renters_path %>

irentex/app/views/renters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Renter name:</strong>
  <%= @renter.renter_name %>
</p>

<p>
  <strong>Renter email:</strong>
  <%= @renter.renter_email %>
</p>

--> <%= link_to 'Edit info', edit_renter_path(@renter) %> |

--> <%= link_to 'log out', logout_path(:renter_id => @renter.id) , method: :delete  %> 