irentex/config/routes.rb
Rails.application.routes.draw do
  resources :renters
  resources :item_attachments
  get 'sessions/new'

  resources :categorys do
  resources :category_filters
  end
  
  get 'home/index'
  root 'home#index'
  resources :users do
      resources :items 
  end
  
resources :reservations

  patch   '/uploadlogo',      to: 'users#uploadlogo'

  get     '/markavailable',   to: 'items#markavailable'
  get	    '/showcat',         to: 'category_items#show'
  get     '/viewitem',        to: 'items#index'
  get     '/changeStatus',    to: 'reservations#changeStatus'

  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  get     '/loginrenter',     to: 'sessions#loginrenter'
  post    '/loginrenter',     to: 'sessions#createrenter'
  post    '/searchItems',     to: 'category_items#searchCat'
  delete  '/logout',          to: 'sessions#destroy'

end

irentex/app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	has_many :item_attachments
	has_one :item_spec
    accepts_nested_attributes_for :item_attachments
	accepts_nested_attributes_for :item_spec

def self.search(search)
  where("item_name LIKE ?", "%#{search}%") 
end

def self.findwithuser(userid)
  where("user_id = ?", "#{userid}") 
end

def self.findbyCat(catid)
  where("category_id = ?", "#{catid}") 
end

def self.findwithcategory(category_id)
  where("category_id LIKE ?", "%#{category_id}%") 
end

def self.findAll( searchCrieria , category_id , arrayOfChexBoxes)
 
$query = " 1 = 1 "
 
 $query  += " AND item_price " + " BETWEEN  " + "#{searchCrieria["FPrice"]}" +" AND " + "#{searchCrieria["TPrice"]}"
 
 
 $ValuesIn = "("

         # puts arrayOfChexBoxes["Color"]
			
			arrayOfChexBoxes["City"].each do |c|
			
			
			if searchCrieria["City_"+c] != nil
				$ValuesIn += "'#{c}' ,"  
			end 	 
		end
			n = $ValuesIn.size
			$ValuesIn = $ValuesIn[0..n-2]
			$ValuesIn += ")" 
			
			if $ValuesIn.size != 2
			
			$query  += " and user_id in (select id from users where users.usr_city in " + $ValuesIn + " )"
			end 
			
 
 
 $query  += " and category_id = " + category_id
 where($query)
end


end

irentex/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user, only: [:show, :new, :markavailable, :create, :edit, :update, :destroy]
	def index
	  @item = Item.find(params[:id])
    @item_attachment = @item.item_attachments.all
    
    labels = []
    @itemSpecs = ItemSpec.findbyItem(params[:id])
    @itemSpecs.each do |is|
         labels.push(CategoryFilter.find(is.category_filter_id).nameOfLabel)
    end
    @labels = labels
    @user = User.find(@item.user_id) 
end

def show
	  @item = Item.find(params[:id])
end

def new
	@user = User.find(params[:user_id])
  @filters =  CategoryFilter.findByCat(@user.categories_id)
  
  @item  = @user.items.build
  @item_attachment = @item.item_attachments.build
end
 
def markavailable
    @item = Item.find(params[:id])
    if (params[:iava] == '0')  #user want to make it available
      @item.update(:item_available => '1')
    else
      #user want to make it not available
      @item.update(:item_available => '0')
    end
    redirect_to user_path(:id => params[:user_id])

end

def create
  @user = User.find(params[:user_id])
 	@item = @user.items.create(item_params)
  @filters =  CategoryFilter.findByCat(@user.categories_id)
  
  
  if @item.save
        params[:item_attachments]['image'].each do |a|
                  @item_attachment = @item.item_attachments.create!(:image => a)
        end
        
        @filters.each do |fi| 
            @itemSpecs = ItemSpec.create( :item_id => @item.id, :category_filter_id => fi.id, :value => params[fi.nameOfLabel]  )
        end
  		  redirect_to user_path(:id => params[:user_id])
	else
  		render :action => 'new'
	end
  	  	
end

def edit
  @item = Item.find(params[:id])
  @itemSpecs = ItemSpec.findbyItem(@item.id)
    @user = User.find(params[:user_id])
  @filters =  CategoryFilter.findByCat(@user.categories_id)

end
	 
def update
  @user = User.find(params[:user_id])
  @item = Item.find(params[:id])

  @filters =  CategoryFilter.findByCat(@user.categories_id)
  @itemSpecs = ItemSpec.findbyItem(@item.id)

  if @item.update(item_params)
      k =0
      @filters.each do |fi| 
            @itemSpecs[k].update(:value => params[fi.nameOfLabel] )
            k = k+1
      end
      redirect_to user_path(:id => params[:user_id])
  else
    render 'edit'
  end
end

def destroy
  @user = User.find(params[:user_id])
  @item = Item.find(params[:id])

  @itemSpecs = ItemSpec.findbyItem(@item.id)

  @itemSpecs.each do |is|
              is.destroy
          end
  @item.destroy

  
  redirect_to user_path(:id => params[:user_id])
end

private
def item_params
	    params.require(:item).permit(:item_name,:item_desc,:item_price,:category_id,:item_available, :item_per, :item_maxp, :item_minp)
end
end

irentex/app/helpers/items_helper.rb
module ItemsHelper
end

irentex/app/views/items/edit.html.erb
<title> Edit Item</title>


<h1>Edit Item</h1>

<%= form_for @item, url: user_item_path, method: :patch   do |u| %>
<table>

	<p>
		<%= u.hidden_field :category_id, :value => @user.categories_id %>
		<tr><td> <%=	u.label :"Item Name:"         %> </td><td>  <%=	u.text_field :item_name  %></td></tr>
		<tr><td> <%=	u.label :"Item Description:"  %> </td><td> <%=	u.text_area :item_desc  %> </td></tr>
		<tr><td> <%=	u.label :"Item Available:"  %> </td><td> <%=	u.text_field :item_available  %> </td></tr>
		<tr><td> <%=	u.label :"Item Price:"        %> </td><td> <%=	u.text_field :item_price %> </td>
		<td> <%=	u.label :"Price per"          %> </td><td>  <%=   u.select(:item_per) do %>
							                        <%[['day','day'], 
							                           ['week', 'week'],
							                           ['month', 'month']].each do |c| -%>
	                                                    <%= content_tag(:option, c.first, value: c.last) %>	
	                                                    <% end %>
	                                                    <% end %>
	    </td></tr>
	    <tr>
	        <td> <%=	u.label :"Rental Period:"     %> </td>
	        <td> <%=	u.text_field :item_maxp, :value =>"max" %> </td>
	      
	        </tr>
	        <tr>
	        	<td></td>
	        	<td> <%=	u.text_field :item_minp, :value =>"min" %> </td>
		  	</tr>

	<tr></tr>	
	<tr><td><strong> Product Spesfications: </strong></td><td></td><td></td></tr>
	<% count =0 
	   @filters.each do |i|   %>
			 	<% if i.typeOfLabel == "text" %>
			 		<tr>
			 			<td><%=i.nameOfLabel%></td>
			 			<td><input type="text" name ="<%=i.nameOfLabel%>" value="<%=@itemSpecs[count].value%>"> </td>
			 		</tr>    
	            <% else %>
	            	<input type="text" name ="F<%=i.nameOfLabel%>" >
					<input type="text" name ="T<%=i.nameOfLabel%>" >
	 	     <% end %>
	         <% count = count+ 1
	    end %>
  <tr>
  <%= u.fields_for :item_attachments do |p| %>
      <td> <%= p.label :image %> </td>
      <td><%= p.file_field :image, :multiple => true, name: "item_attachments[image][]" %></td>
   <% end %>
 </tr>

   <tr><td> <%=u.submit %></td><td></td></tr>

</table>

<% end %>

<%= link_to 'Back', user_path(:id => params[:user_id]) %>

irentex/app/views/items/index.html.erb
<h3><%= @item.item_name %></h3>
      
<p id="notice"></p>
<table style="width: 50%">
  <tr>
    <th>item images</th>
    <th colspan="3"></th>
  </tr>

  <tr>
    <% @item.item_attachments.all.each do |p| %>
       <td>  <%= image_tag p.image.thumb2.url%> </td>
      <% end %>
  </tr>

</table>

<table style="width: 50%">
  <tr>
    <th>Item Description</th>
    <th>Item Price</th>
    <% @labels.each do |label| %>
      <th><%= label%></th>
    <%end%>
    <th colspan="3"></th>
  </tr>
  <tr>
      <td><%= @item.item_desc %></td>
      <td><%= @item.item_price %></td>
      <% @itemSpecs.each do |itemspec| %>
        <td><%= itemspec.value %></td>
     <%end%>

    </tr>
</table>

<h3> Vendor Info: </h3>
<p id="notice"><%= notice %></p>
  <strong>Vendor Name:</strong> <%= @user.usr_vname %> <br>
  <strong>logo:</strong> <%= image_tag @user.usr_logo.thumb %> <br>
  <b>Description:              </b> <%= @user.usr_description  %> <br>
  <b>Delivery option:                 </b> <% if @user.usr_delivery == 0 %> 
                                         <%= :"home" %>
                                     <% else 
                                           if  @user.usr_delivery == 1 %>
                                                <%= :"shop" %>
                                            <% else %>
                                                <%= :"home & shop" %>
                                            <% end %>
                                       <% end %> <br>

  <b>Your Address is:          </b> <%= @user.usr_address  %> , <%=h @user.usr_gover  %> <br>
  <b>Telephone no.: </b> <%= @user.usr_tel  %>   <br> 
<br>

<h3> Request Form </h3>
<%= form_for :reservation , url: reservations_path(:id => @item.id) do |u| %>
    <%= u.hidden_field :item_id, :value => @item.id %>
    <%= u.hidden_field :status, :value => "0" %>
    Name:  <%= text_field(:reservation, :name)  %> <br>
    Email: <%= text_field(:reservation, :email) %> <br>
    Form:  <%= text_field(:reservation, :from , id: "from" )  %> <br>
    To  :  <%= text_field(:reservation, :to, id: "to")    %> <br>
    <br>
<%=u.submit "Reserve Now!", class: "btn btn-primary"  %>
<%end%>

irentex/app/views/items/new.html.erb
<title> Add New Item</title>

<%= link_to 'Back', user_path(:id => params[:user_id]) %>

<h1>Add New Item</h1>

<%= form_for :item, url: user_items_path  do |u| %>
<table>
  <tr>
    <th><%= u.hidden_field :category_id, :value => @user.categories_id %></th>
    <th><%= u.hidden_field :item_available, :value => :"1" %></th>
    <th></th>
  </tr>
  <tr>
    <td> <%=	u.label :"Item Name:"         %></td>
    <td> <%=	u.text_field :item_name  %></td>
  </tr>
  <tr>
    <td> <%=	u.label :"Item Description:"  %> </td>
    <td> <%=	u.text_area :item_desc  %> </td>
    <td></td>
  </tr>
  <tr>
    <td><%=	u.label :"Item Price:"        %></td>
    <td><%=	u.text_field :item_price %></td>
    <td><%=	u.label :"Price per"          %> <%=   u.select(:item_per) do %>
							                        <%[['day','day'], 
							                           ['week', 'week'],
							                           ['month', 'month']].each do |c| -%>
	                                                    <%= content_tag(:option, c.first, value: c.last) %>	
	                                                    <% end %>
	                                                    <% end %></td>
  </tr>
  <tr>
    <td><%=	u.label :"Rental Period:"     %> </td>
    <td><%=	u.text_field :item_maxp, :value =>"max" %></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><%=	u.text_field :item_minp, :value =>"min" %></td>
    <td></td>
  </tr>
  
  <tr>
    <td><strong> Product Spesfications: </strong></td>
    <td></td>
    <td></td>
  </tr>
	<% count =0 
	   @filters.each do |i| %>
			 	<% if i.typeOfLabel == "text" %>
			 		<tr>
			 			<td><%=i.nameOfLabel%></td>
			 			<td><input type="text" name ="<%=i.nameOfLabel%>"> </td>
			 			<td></td>
			 		</tr>    
	            <% else %>
	            	<input type="text" name ="F<%=i.nameOfLabel%>" >
					<input type="text" name ="T<%=i.nameOfLabel%>" >
	 	     <% end %>
	         <% count = count+ 1
	    end %>
  <tr>
  <%= u.fields_for :item_attachments do |p| %>
      <td> <%= p.label :image %> </td>
      <td><%= p.file_field :image, :multiple => true, name: "item_attachments[image][]" %></td>
      <td></td>
   <% end %>
 </tr>

  <tr>
    <td><%=u.submit %></td>
    <td></td>
    <td></td>
  </tr>
</table>
<% end %>

irentex/app/views/items/show.html.erb
<table style="width: 50%">
  <tr>
    <th>Item Name</th>
    <th>Item Description</th>
    <th>Item Price</th>
    <th colspan="3"></th>
  </tr>
  <tr>
      <td><%= @item.item_name %></td>
      <td><%= @item.item_desc %></td>
      <td><%= @item.item_price %></td>

    </tr>
</table>

<table style="width: 50%">
  <tr>
    <th>item images</th>
    <th colspan="3"></th>
  </tr>

  <% @item.item_attachments.all.each do |p| %>
   <tr>
      <td><%= image_tag p.image.thumb.url %></td>
      <td><%= link_to "show original", item_attachment_path(p) %></td>  
      <td><%= link_to "Edit Attachment", edit_item_attachment_path(p) %></td>
    </tr>

      <% end %>
</table>
<%= link_to 'Back', user_path(:id => params[:user_id]) %>