irentex/config/routes.rb
Rails.application.routes.draw do
  resources :renters
  resources :item_attachments
  get 'sessions/new'

  resources :categorys do
  resources :category_filters
  end
  
  get 'home/index'
  root 'home#index'
  resources :users do
      resources :items 
  end
  
resources :reservations

  patch   '/uploadlogo',      to: 'users#uploadlogo'

  get     '/markavailable',   to: 'items#markavailable'
  get	    '/showcat',         to: 'category_items#show'
  get     '/viewitem',        to: 'items#index'
  get     '/changeStatus',    to: 'reservations#changeStatus'

  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  get     '/loginrenter',     to: 'sessions#loginrenter'
  post    '/loginrenter',     to: 'sessions#createrenter'
  post    '/searchItems',     to: 'category_items#searchCat'
  delete  '/logout',          to: 'sessions#destroy'

end

irentex/app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :usr_logo, ImageUploader

    has_many :items
	accepts_nested_attributes_for :items
	
	has_secure_password
end

irentex/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:index, :show, :upload, :edit, :uploadlogo, :update, :destroy]
	def index
	  @user = User.find(params[:id])
	end
	
	def show
	  @user = User.find(params[:id])
	  @items = Item.findwithuser(params[:id])
	  
	  @user_category = Category.find(@user.categories_id)
	  @filters 		 = CategoryFilter.findByCat(@user.categories_id)
	  

	  labels 		 = []
	  itemspecs_all  = []
	  reservations    = []


	  flag = 0
	  @items.each do |i|
	  		
	  		@reservation = Reservation.findbyItem(i.id)
			reservations.push(@reservation)
			
	  		@itemSpecs   = ItemSpec.findbyItem(i.id)
	  		itemspecs_all.push(@itemSpecs)
	  		if flag == 0 
	  			@itemSpecs.each do |is|
	  					labels.push(CategoryFilter.find(is.category_filter_id).nameOfLabel)
	  			end
	  		end
	  		flag = 1

	  end 
	  
	  @labels = labels
	  @itemspecs_all = itemspecs_all
	  @reservations	 = reservations
	end


	def uploadlogo
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "logo was successfully added :)"
			redirect_to user_path(@user.id)
		else
			flash[:notice] = "failed to update logo :("
			redirect_to user_path(@user.id)
		end	
	end

	def new
	  @categories = Category.all
	end

 
	def create
		@categories = Category.all
	 	@user = User.new(user_params)	  	
	  	if @user.save
      		flash[:notice] = "Successfully sign up"
      		redirect_to user_path(@user.id)
    	else
      		render :action => 'new'
    	end
	  	
	end
	 
	 def edit
	  @user = User.find(params[:id])
	  @categories = Category.all
	end


	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "updated :)"
			redirect_to user_path(@user.id)
		else
			flash[:notice] = "failed :("
			redirect_to user_path(@user.id)
		end	
	end
	def destroy
	  @user = User.find(params[:id])

	  @user.destroy
	 
	  redirect_to home_index_path
	end
	private
	  def user_params
	    params.require(:user).permit(:usr_vname,:usr_description,:usr_email,:password, :password_confirmation,:usr_tel,:usr_address,:usr_gover,:categories_id, :usr_logo,:usr_delivery,:usr_city)
	  end

end

irentex/app/helpers/user_helper.rb
module UserHelper
end

irentex/app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for @user , url: user_path , method: :patch  do |u| %>

	<%=	u.label :"Vendor Name" %>
	<%=	u.text_field :usr_vname , class: 'form-control' %> <br> 


	<%=	u.label :"Category:"  %>  
	<%= 	u.select(:categories_id) do %>
	<% 			@categories.each do |c| -%>
	<%= 		content_tag(:option, c.CategoryName , value: c.id) %>	
			<% end %>
    <% end %>

    <br> 

    <%=	u.label :"short description:" %>
	<%=	u.text_area :usr_description,  class: 'form-control' %> <br> 

	<%=	u.label :"email"  %>  
	<%= u.text_field :usr_email, class: 'form-control' %><br> 

	<%=	u.label :"Password"  %>
	<%= u.password_field :password, class: 'form-control' %><br> 

	<%=	u.label :"Password confirmation"  %> <br> 
	<%=	u.password_field :password_confirmation , class: 'form-control' %> <br> 

	<%=	u.label :"telephone no."  %> 
	<%= u.text_field :usr_tel, class: 'form-control' %><br> 

	<%=	u.label :"Address:"  %> <br> 
	<%= u.text_field :usr_address, class: 'form-control' %> <br> 
	
	<%=	u.label :"Governorates:"  %>  
	<%= u.select(:usr_gover) do %>
							 <%[['Alexandria','Alexandria'], 
		    					['Aswan', 'Aswan'], 
		    					['Asyut', 'Asyut'], 
								['Beheira', 'Beheira'],
								['Beni Suef', 'Beni Suef'], 
								['Cairo', 'Cairo'], 
								['Dakahlia', 'Dakahlia'], 
								['Damietta', 'Damietta'], 
								['Faiyum', 'Faiyum'], 
								['Gharbia', 'Gharbia'],  
								['Giza', 'Giza'], 
								['Ismailia', 'Ismailia'], 
								['Kafr El Sheikh', 'Kafr El Sheikh'], 
								['Luxor', 'Luxor'], 
								['Matruh', 'Matruh'], 
								['Minya', 'Minya'], 
								['Monufia', 'Monufia'], 
								['North Sinai', 'North Sinai'],
								['New Valley', 'New Valley'],
								['Port Said', 'Port Said'],
								['Qalyubia', 'Qalyubia'],
								['Red Sea', 'Red Sea'],
								['Sharqia', 'Sharqia'],
								['Sohag', 'Sohag'],
								['South Sinai', 'South Sinai'],
								['Suez', 'Suez'] ].each do |c| -%>
	<%= content_tag(:option, c.first, value: c.last) %>	

  <% end %>
<% end %>
	
<%=	u.label :"delivery option:"  %>  
	<%= u.select(:usr_delivery) do %>
							 <%[['home','0'], 
		    					['at shop', '1'], 
		    					['both ', '2'] ].each do |c| -%>
	<%= content_tag(:option, c.first, value: c.last) %>	

  <% end %>
<% end %>


    <br>  
<p>
  <%=u.submit "Update", class: "btn btn-primary"  %>
</p>
<% end %>


  </div>
</div>

irentex/app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for :user , url: users_path do |u| %>

	<%=	u.label :"Vendor Name" %>
	<%=	u.text_field :usr_vname,  class: 'form-control' %> <br> 


	<%=	u.label :"Category:"  %>  
	<%= 	u.select(:categories_id) do %>
	<% 			@categories.each do |c| -%>
	<%= 		content_tag(:option, c.CategoryName , value: c.id) %>	
			<% end %>
    <% end %>

    <br> 

    <%=	u.label :"short description:" %>
	<%=	u.text_area :usr_description,  class: 'form-control' %> <br> 

	<%=	u.label :"email"  %>  
	<%= u.text_field :usr_email, class: 'form-control' %><br> 

	<%=	u.label :"Password"  %>
	<%= u.password_field :password, class: 'form-control' %><br> 

	<%=	u.label :"Password confirmation"  %> <br> 
	<%=	u.password_field :password_confirmation , class: 'form-control' %> <br> 

	<%=	u.label :"telephone no."  %> 
	<%= u.text_field :usr_tel, class: 'form-control' %><br> 

	<%=	u.label :"Address:"  %> <br> 
	<%= u.text_field :usr_address, class: 'form-control' %> <br> 
	
	<%=	u.label :"City:"  %> <br> 
	<%= u.text_field :usr_city, class: 'form-control' %> <br> 
	

	<%=	u.label :"Governorates:"  %>  
	<%= u.select(:usr_gover) do %>
							 <%[['Alexandria','Alexandria'], 
		    					['Aswan', 'Aswan'], 
		    					['Asyut', 'Asyut'], 
								['Beheira', 'Beheira'],
								['Beni Suef', 'Beni Suef'], 
								['Cairo', 'Cairo'], 
								['Dakahlia', 'Dakahlia'], 
								['Damietta', 'Damietta'], 
								['Faiyum', 'Faiyum'], 
								['Gharbia', 'Gharbia'],  
								['Giza', 'Giza'], 
								['Ismailia', 'Ismailia'], 
								['Kafr El Sheikh', 'Kafr El Sheikh'], 
								['Luxor', 'Luxor'], 
								['Matruh', 'Matruh'], 
								['Minya', 'Minya'], 
								['Monufia', 'Monufia'], 
								['North Sinai', 'North Sinai'],
								['New Valley', 'New Valley'],
								['Port Said', 'Port Said'],
								['Qalyubia', 'Qalyubia'],
								['Red Sea', 'Red Sea'],
								['Sharqia', 'Sharqia'],
								['Sohag', 'Sohag'],
								['South Sinai', 'South Sinai'],
								['Suez', 'Suez'] ].each do |c| -%>
	<%= content_tag(:option, c.first, value: c.last) %>	

  <% end %>
<% end %>
	
<%=	u.label :"delivery option:"  %>  
	<%= u.select(:usr_delivery) do %>
							 <%[['home','0'], 
		    					['at shop', '1'], 
		    					['both ', '2'] ].each do |c| -%>
	<%= content_tag(:option, c.first, value: c.last) %>	

  <% end %>
<% end %>


    <br>  
<p>
  <%=u.submit "Sign up", class: "btn btn-primary"  %>
</p>
<% end %>


  </div>
</div>

irentex/app/views/users/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<p><%= link_to '+add item', new_user_item_path(@user.id) %></p>
<p>
	<b>Welcome </b> <%=	@user.usr_vname  %> !
</p>
<br>
<br>
<p id="notice"><%= notice %></p>
 <strong>logo:</strong> <%= image_tag @user.usr_logo.thumb %>
<br>
<%= form_for @user, url: uploadlogo_path(:id => @user.id)   do |f| %>
    <p><%= f.file_field :usr_logo  %> <br>
       <%=f.submit "upload logo", class: "btn btn-primary"  %></p>
<% end %>
<br>
<br>
<p>
	<b>logged-in via:            </b> <%=	@user.usr_email  %> <br>
	<b>Registered telephone no.: </b> <%=	@user.usr_tel  %>   <br> 
  <b>Description:              </b> <%=	@user.usr_description  %> <br>
  <b>Delivery:                 </b> <% if @user.usr_delivery == 0 %> 
                                         <%= :"home" %>
                                     <% else 
                                           if  @user.usr_delivery == 1 %>
                                                <%= :"shop" %>
                                            <% else %>
                                                <%= :"home & shop" %>
                                            <% end %>
                                       <% end %> <br>
	<b>Your Address is:          </b> <%= @user.usr_address  %> , <%=h @user.usr_gover  %> <br>
	<b>Your Category is:         </b> <%= @user_category.CategoryName%>
</p>
<h3>Reservations:</h3>
<table border="1">
  <tr>
    <th>Product no: </th>
    <th>Requester Name :</th>
    <th>Requester Email:</th>
    <th>Request Date <br>From --> date </th>
    <th>:</th>
  </tr>
  <% @reservations.each do |rr| %>
    <% rr.each do |r| %>
            <tr>
              <td> <%= r.item_id %></td>
              <td> <%= r.name %></td>
              <td> <%= r.email %></td>
              <td> <%= r.from %> --> <%= r.to %> </td>
              <td> <% if r.status == 0 %>
              <%=  :"new request" %>
                <td> <%= link_to "accept", changeStatus_path(:id => r.id ,:user_id => @user.id, :status =>'1') %></td>
                 <td> <%= link_to "reject", changeStatus_path(:id => r.id ,:user_id => @user.id, :status =>'2') %></td>
                   <% else 
                      if r.status == 1 %>
                        <%=  :"accepted" %>
                    <%else %>
                        <%=  :"rejected" %>
                   <%end%>
                   <%end%>
              </td> 
            </tr>
        <% end %> 
        <% end %> 
</table>

<h3>Items:</h3>
<table border="1">
  <tr>
    <th>Item ID</th>
    <th>Item Name</th>
    <th>Item Description</th>
    <th style="width:50%" >Item Images</th>
    <th>Item Price</th>
    <% @labels.each do |i| %>
            <th><%=i%></th>
      <%end %>
    <th colspan="4"></th>
  </tr>
<% j =0
  @items.each do |i| %>
<tr>
      <td><%= i.id %></td>
      <td><%= i.item_name %></td>
      <td><%= i.item_desc %></td>
      <td>
      <table>
        <% i.item_attachments.all.each do |p| %>
            <tr>
              <td> <%= image_tag p.image.thumb.url %></td>
              <td> <%= link_to "show image", item_attachment_path(p) %></td>
              <td> <%= link_to "Edit image", edit_item_attachment_path(p) %></td>
            </tr>
        <% end %> 
      </table> </td>
      <td><%= i.item_price %></td>
      <% if j<@itemspecs_all.length
          @itemspecs_all[j].each do |k| %>
                <td>  <%= k.value %></td>      
          <% end %>
         <% j= j+1 %> 
         <% end%>

      <td><% if i.item_available == 0 %>
            <%= link_to 'mark available', markavailable_path(:user_id => i.user_id, :id => i.id, :iava => i.item_available) %>
          <% else %>
            <%= link_to 'mark unavailable', markavailable_path(:user_id => i.user_id,:id => i.id, :iava => i.item_available) %>
          <% end %>
            </td>
      <td><%= link_to 'Show', user_item_path(:id => i.id     , :user_id => i.user_id) %></td>
      <td><%= link_to 'Edit', edit_user_item_path(:id => i.id, :user_id => i.user_id) %></td>
      <td><%= link_to 'Destroy', user_item_path(:id => i.id  , :user_id => i.user_id),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>

</table>

<br><br>
--> <%= link_to 'update info', edit_user_path(@user) %> <br>

--> <%= link_to 'delete account', user_path(:id => @user.id),
              method: :delete,
              data: { confirm: 'Are you sure?' } %> <br>

--> <%= link_to 'log out', logout_path(:user_id => @user.id) , method: :delete  %> 
</div>
</div>